### ISSUE TITLE
Fonts/ Item width changes?

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [braheezy/catppuccin-gtk-rpm#3]
Hey,
First of all amazing work! I didn't use your RPMs but got the theme from the main catpuccin gtk repository and installed them in the user folder and changed the source theme directory to /home/{username}/.themes/ and everything worked.

2 things - 
1. In the gnome-shell-theme.gresource.xml, the line <file>assets/toggle-off-dark.svg</file> is not required anymore, since I guess the original theme removed it.

2. After I implement the theme, the fonts and item widths start looking squished - 
Before - 

https://github.com/braheezy/catppuccin-gtk-rpm/assets/98815412/97a57bf3-b512-4afd-9e1d-3051d1b9964b

After - 

[Screencast from 2023-05-14 17-00-51 (copy).webm](https://github.com/braheezy/catppuccin-gtk-rpm/assets/98815412/48308ade-4f42-43b5-bbe1-281c1f79eef4)

Anyway to resolve this?

Thanks!

PS - Testing was done on a VM

**Comment by braheezy** [comment]
Hi! I am not affiliated with the Catppuccin project in any way but I'll share what I have working.

I currently use [v0.4.1](https://github.com/catppuccin/gtk/releases/tag/v0.4.1) of the GTK theme on Fedora 37 with GNOME 43.5. I'm not seeing this text problem.

I don't use this RPM anymore. But this set of Ansible tasks from my [dotfiles](https://github.com/braheezy/dotfiles/blob/master/roles/gnome/tasks/customize_gtk.yml) show some of the steps I take to install and configure the theme:
```yml
- name: Download GTK theme
  ansible.builtin.get_url:
    url: https://github.com/catppuccin/gtk/releases/download/v0.4.1/Catppuccin-Mocha-Standard-Mauve-Dark.zip
    dest: /tmp/
    mode: 0755

- name: Install GTK theme
  become: true
  ansible.builtin.unarchive:
    src: /tmp/Catppuccin-Mocha-Standard-Mauve-Dark.zip
    dest: /usr/share/themes/
    mode: 0755

- name: Set GTK theme
  community.general.dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Catppuccin-Mocha-Standard-Mauve-Dark'"
    state: present

- name: Ensure gtk-4 folder exists
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.config/gtk-4.0/'
    state: directory
    mode: 0755

- name: Ensure gtk-4 symlinks are present
  ansible.builtin.file:
    src: /usr/share/themes/Catppuccin-Mocha-Standard-Mauve-Dark/gtk-4.0/{{ item }}
    dest: '{{ ansible_env.HOME }}/.config/gtk-4.0/{{ item }}'
    state: link
    mode: 0755
  loop:
    - assets
    - gtk.css
    - gtk-dark.css
```

Otherwise, you'll probably want to open an [issue with Catppuccin GTK](https://github.com/catppuccin/gtk/issues) maintainers. Good luck!
